on: ["push", "pull_request"]

name: Test

concurrency:
  # Cancel older, in-progress jobs from the same PR, same workflow.
  # use run_id if the job is triggered by a push to ensure
  # push-triggered jobs to not get canceled.
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
    linting:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4

        - name: Setup Python
          uses: actions/setup-python@v5
          with:
              python-version: "3.12"

        - name: Install Dependencies
          run: |
            python -m pip install --upgrade pip
            python -m pip install poetry
            poetry install

        - name: Run Black
          run: black --check .

        - name: Run isort
          run: isort --check-only .

    type-check:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4

        - name: Setup Python
          uses: actions/setup-python@v5
          with:
              python-version: "3.12"

        - name: Install Dependencies
          run: |
            python -m pip install --upgrade pip
            python -m pip install poetry
            poetry install

        - name: Run MyPy
          run: mypy .

    test:
        runs-on: ubuntu-latest

        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Setup Python
          uses: actions/setup-python@v5
          with:
              python-version: "3.12"

        - name: Install Dependencies
          run: |
            python -m pip install --upgrade pip
            python -m pip install poetry
            poetry install

        - name: Run Functional Tests
          run: pytest tests/functional -m "not fuzzing" -s --cov=src --cov-append -n auto --dist loadgroup

        - name: Run Integration Tests
          run: pytest tests/integration -m "not fuzzing" -s --cov=src --cov-append -n auto --dist loadgroup

        - name: Run Performance Tests
          run: pytest tests/performance -s

    fuzzing:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: true

        steps:
        - uses: actions/checkout@v4

        - name: Setup Python
          uses: actions/setup-python@v5
          with:
              python-version: "3.12"

        - name: Install Dependencies
          run: |
            python -m pip install --upgrade pip
            python -m pip install poetry
            poetry install

        - name: Run Tests
          run: poetry run pytest -m "fuzzing" --no-cov -s
